name: paperbuddy
description: "PaperBuddy – Dokumente verwalten"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  paperbuddy_api:
    path: ../packages/paperbuddy_api
  http: ^1.6.0
  flutter_secure_storage: ^11.2.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  file_picker: ^13.1.0
  lucide_icons_flutter: ^3.1.21
  flutter_localizations:
    sdk: flutter
  pdfrx: ^2.4.8
  share_plus: ^13.3.1
  cunning_document_scanner: ^3.0.3
  pdf: ^3.13.1
  image: ^4.10.1
  cupertino_icons: ^2.0.0
  url_launcher: ^6.3.3
  receive_sharing_intent: ^1.9.0
  path: ^1.9.1
  qr: ^3.0.2
  desktop_drop: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  paperbuddy_server:
    path: ../server
  shelf: ^1.4.2
flutter:
  uses-material-design: true
